# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe58b9550d9c375cfe75fee067bc260b489a9d850863f33b8267bc2ee22b7d1ee35bc0d0f3ea34b29c67e8a598ab6a55ec829869913f8649b8030d5b41ed5e36

test:
  secret_key_base: 3df17ec6f2a1d5080044d6490f277170401855b38ab644dd812c36b03d0eab941c88c828ea6038ebc1526f477ee9c7bcb4751031edb6e5417d7b624fc23feea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
